version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "21:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config-base'
    schedule:
      interval: 'daily'
      time: "21:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config-react'
    schedule:
      interval: 'daily'
      time: "21:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5
