name: CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    name: 'Lint'

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Deps
        run: |
          yarn install

      - name: Lint
        run: |
          yarn lint
